#pragma once
void run_rng_tests(void);
void run_model_tests(void);
void run_needs_tests(void);
void run_states_tests(void);
void run_discipline_tests(void);
void run_evolution_tests(void);
void run_integration_tests(void);
void run_save_tests(void);
void run_overnight_tests(void);
void run_hunt_tests(void);
void run_hunt_logic_tests(void);
